apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: infra
spec:
  project: default


  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      helm:
        valueFiles:
        - $values/infra/argocd/values.yaml
      targetRevision: v9.1.0 
      chart: argo-cd
    - repoURL: 'https://github.com/Oxsw1ng/homelab.git'
      targetRevision: main
      ref : values

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true